name: loading_button
description: A new Flutter package.
version: 0.0.8

homepage: https://github.com/tipu0710/loading_button.git

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: